services:
  postgres:
    cap_add:
      - NET_ADMIN # Importante para usar firewall (NFTables)
    env_file:
      - .env
    image: database:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        PASSWORD: ${PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
        POSTGRESQL_VERSION: ${POSTGRESQL_VERSION}
    container_name: postgres
    ports:
      - "5433:5432"
      - "8080:80"
      - "9051:9050"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - home:/home/${USER}
    restart: unless-stopped
    # networks:
    #   - backend

volumes:
  pg_data:
  home:

# networks:
#   backend:
